-- This file contains all CREATE PROCEDURE statements for the New Zealand Hospital Doctor Channeling System.
-- Run after tables.sql is executed.

-- ...existing code...
-- (All CREATE PROCEDURE statements go here, deduplicated and cleaned)
-- ...existing code...
